### ISSUE TITLE
base will not download

### ISSUE THREAD

**Issue by Loagn7766** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#12]
base will not download all the way

**Comment by Loagn7766** [comment]
fixed

**Comment by Abro61209** [comment]
bruh just says fixed not how they fixed it

**Comment by ZestyTS** [comment]
@Abro61209 It's probably because they thought it wasn't downloading while it was. Are you trying to inject a GCN or a Wii game? If the answer is no, then the base should download in less than 5 minutes. If the answer is yes, then it might be because of what the base is. Xenoblade Chronicles takes a very long time to get, there are reports of more than an hour. Internet speed does play a role in this, the game is ~8.2GB.
