### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by ThommoMC** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#47]
When will full Linux support be added? Not all injectors work for me and using a VM is annoying.

**Comment by ZestyTS** [comment]
Linux support will not be added to this project.

**Comment by ZestyTS** [comment]
I'm returning to comment on this because I see it gets downvoted, and I know Linux is a request for this project. The reason as to why Linux support will not be added to the project is because I already attempted it a few months earlier from the request, and it didn't work. The project's foundation causes it to be rooted in Windows, it's not something that can easily be done. I speak more about it here #67

**Comment by ZestyTS** [comment]
So, I made UWUVCI support via things like Wine, but it isn't 1 to 1 with the Windows OS version. Version 4 of UWUVCI will support multiple platform, just Version 3's foundation (WPF) is native to Windows only.

**Comment by AlphaCraft9658** [comment]
> So, I made UWUVCI support via things like Wine, but it isn't 1 to 1 with the Windows OS version. Version 4 of UWUVCI will support multiple platform, just Version 3's foundation (WPF) is native to Windows only.

Is a version 4 still planned? I would really like to use UWUVCI on my machine, but it just fails when patching.

**Comment by ZestyTS** [comment]
Version 4 is still being made, it's just a complete rewrite of everything since the foundation of V3 is why it doesn't work on Mac and Linux.
