### ISSUE TITLE
Crash while select Narikiri Dungeon 3 (translated) in GBA inject mode

### ISSUE THREAD

**Issue by NyxiaSha** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#55]
default setting, first step just select rom file, done then crash . Try the raw rom, its successd. [https://drive.google.com/file/d/18Y7VuFGAh-JRlvIRhcw6vgRPhFMYrY8H/view?usp=sharing](url) this i used rom

**Comment by NicoAICP** [comment]
Is this really the rom you used or just the instructions?
If you really used the "ROM" in the link you posted then its no wonder, since this is a pdf

**Comment by NyxiaSha** [comment]
> Is this really the rom you used or just the instructions? If you really used the "ROM" in the link you posted then its no wonder, since this is a pdf

I changed the Filename Extension，prevent some drive rule。Deleted .pdf its my used rom。 ROM already try run in Retroarch mGBA core， correct running

**Comment by ZestyTS** [comment]
It took me a while to understand your question, but I know what the problem is. It has to do with the patch that was applied to the Rom removing needed data. Emulators don't need all the data of the rom to work, which is why you aren't seeing this problem elsewhere.

In this picture you'll see that I highlighted the problem, there should be a value here, but your rom is just blank.
![image](https://github.com/user-attachments/assets/9cc86547-30c4-41e9-8025-b0ed375fc584)

Here's what it looks like when I load in the game called "Creatures" so you can see an example of what's expected.
![image](https://github.com/user-attachments/assets/6b9a9ae1-50d6-4d0b-8ed9-e42fdbc5b539)

Technically, you could put anything in there, I just used it's full name since it looked like it would fit.
![image](https://github.com/user-attachments/assets/91e65634-f9ba-4ef4-aa4a-540f24cf8322)

But realistically, you should look at the original game, check to see what value is and update the patched rom to have it, and it'll work, as you can see here.
![image](https://github.com/user-attachments/assets/378cf433-ce26-41cb-946a-66f3b2a3c01e)
