### ISSUE TITLE
Homebrew injections don't work (at least Nintendont)

### ISSUE THREAD

**Issue by TCAtrevor** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#61]
I'm trying to make a Nintendont injection on the latest version and it is just getting stuck on this loading bar (Setting Up C2W - Please Wait). I have no idea which version it stopped working in but neither me nor a friend of mine were able to create the injection on the latest version. I tried regressing one version to 3.F.F and it did not work either. It has been over 2 years since I last made this injection.

![image](https://github.com/stuff-by-3-random-dudes/UWUVCI-AIO-WPF/assets/16995298/a8cfa506-eff7-4eda-896b-a3c15bde81ac)

Some miscellaneous info:
BaseRom is Rhythm Heaven Fever US
Nintendont "loader.dol" downloaded from https://github.com/FIX94/Nintendont

**Comment by TCAtrevor** [comment]
Went back to 3.0.3 (didn't check any other versions in between) and the injection worked.

**Comment by TCAtrevor** [comment]
![image](https://github.com/stuff-by-3-random-dudes/UWUVCI-AIO-WPF/assets/16995298/6de021d4-2035-4ade-ab07-f84c32d26d0f)
This is how it is set up, and when I press "Inject" it gets stuck immediately on Setting up C2W.

**Comment by ZestyTS** [comment]
Oh, you're not injecting GCN games, you're straight up trying to inject Nintendont. So, I guess the question I would have for you is why are you doing it this way? AFAIK, you gain nothing for using c2w with Nintendont, so just don't put in the ancast key.

**Comment by TCAtrevor** [comment]
Oh, I see. Didn't realize the ancast key was optional. No idea what C2W even is, and I was even wondering why the older version that worked didn't have me put that key in. Very confusing the way that is implemented, I guess.

**Comment by TCAtrevor** [comment]
Does it not get stuck on Setting up C2W for other apps then? I would still say it's an issue that it can just get stuck like that without giving any sign of what it's trying to do.

**Comment by ZestyTS** [comment]
When I made this and tested it, it never got stuck for me, and it's been part of UWUVCI for more than 15 months, so if someone else had problems they would have mentioned it. All of the tools can get stuck like that because of how everything works. Any time you see that pop-up window come up, it means it's calling an external tool and waiting for the eternal tool to finish, if it doesn't it hangs. This project hasn't been in active development since Oct 2022, so unless it's making the entire program not function, it's fine how it is.
