### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by Magnusretrotech** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#67]
Could someone port this to Linux?

**Comment by ZestyTS** [comment]
I attempted to do this with the 3.99x releases, but so much of the foundation of the code would have to be rewritten that you're better off making a new version. Currently, we are remaking this entire project to be cross platform, but that's further away than it is closer.

If someone really wanted to attempt this, they would need to go in and recreate all of the tools that are exe files and make them libraries. Since the project uses .Net Framework, you could get away with using it by utilizing Mono. If you wanted it to be a Linux executable, then you would need to convert the entire project to .Net and update the tools and libraries to be .Net Standard at the very least.

**Comment by ZestyTS** [comment]
Just published a "new" version that allows UWUVCI 3 to work under Wine, but it doesn't cover all of the external tools that UWUVCI uses. This is the best you're getting until UWUVCI 4 comes out.
