### ISSUE TITLE
WUP Package not showing up in WUP Installer GX2

### ISSUE THREAD

**Issue by Literalgamer81** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#68]
I recently downloaded UWUVCI and created a WUP install of Mario Kart Wii. I copied it over to my sd card and opened up WUP Installer GX2. However, the WUP Package of Mario Kart Wii didn't show up. Other WUP packages that weren't from UWUVCI did show up.

**Comment by ZestyTS** [comment]
Did you try manually copying it over?

**Comment by Literalgamer81** [comment]
No I used the copy to sd card tool. I'll try manualy right now.

**Comment by Literalgamer81** [comment]
I  copied over the file and it was empty.

**Comment by Literalgamer81** [comment]
I just had to disable my antivirus. Thank you for the help.

**Comment by ZestyTS** [comment]
Makes sense. It's part of the reason why antivirus is listed as a thing that can mess with the program, it's somewhere on the FAQ which is in the ReadMe.txt file. Unrelated to UWUVCI, but I highly suggest not using antivirus software unless it's Windows Defender because they usually make it so you are more likely to get problems and viruses. I recommend looking it up.
